name: epub_view_2
description: Flutter widget for view EPUB documents on on Web, MacOs, Android and iOS. Based on dart-epub package.
repository: https://github.com/yokohailemariam/epub_view_2
issue_tracker: https://github.com/yokohailemariam/epub_view_2/issues
version: 3.2.0

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  epubx: ^4.0.0
  equatable: ^2.0.5
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  scrollable_positioned_list: ^0.3.8
  collection: ^1.17.1
  universal_file: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
